version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: ./my-app/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./my-app/src:/app/src
    links:
      - "server:server"

  server:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    depends_on:
      - postgres
    ports:
      - "8080:8080"

  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
    ports:
        - 5432:5432
    volumes:
      - dbdata:/var/lib/postgresql/data

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/templates:/etc/nginx/templates
    depends_on:
      - web
      - server
    environment:
      FRONTEND_COMPOSE_SERVICE_NAME: ${FRONTEND_COMPOSE_SERVICE_NAME}
      FRONTEND_PORT: ${FRONTEND_PORT}
      BACKEND_COMPOSE_SERVICE_NAME: ${BACKEND_COMPOSE_SERVICE_NAME}
      BACKEND_PORT: ${BACKEND_PORT}
    

volumes:
  dbdata: