version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: ./my-app/Dockerfile
    ports:
      - "3000:3000"

  server:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    depends_on:
      - postgres
    ports:
      - "8080:8080"

  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: personal_finance_su
      POSTGRES_PASSWORD: password123!
      POSTGRES_DB: personal_finance_app
    ports:
        - 5432:5432
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata: